name = "dropdown-email-worker"
main = "worker.js"
compatibility_date = "2025-08-11"
type = "javascript"
account_id = "85221db225a51b1c70076848e8c20111"
workers_dev = true
[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

# KV Namespace
[[kv_namespaces]]
binding = "SIGNIN_LOGS"
id = "21170895129f4be28c3f40ca676dc1ea"
preview_id = "21170895129f4be28c3f40ca676dc1ea" # same as id if no separate preview namespace

[[kv_namespaces]]
binding = "SESSION_STATE"
id = "9af89a52da844c5bae5ef2bab7e4f375"
preview_id = "9af89a52da844c5bae5ef2bab7e4f375" # same as id if no separate preview namespace

[[d1_databases]]
binding = "araa_testing"
database_name = "araa_testing"
dtabase_id = "1676ab2e-74e7-4b7e-b84c-b4c45adeb40c"